# Generated by Django 3.0.6 on 2020-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid_tb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=30)),
                ('covid_strain', models.CharField(max_length=1)),
                ('pre_exisiting', models.CharField(max_length=50)),
                ('hospitalised', models.CharField(max_length=1)),
                ('medicine_applied', models.CharField(max_length=1)),
                ('current_status', models.CharField(max_length=1)),
            ],
        ),
    ]
