# Generated by Django 3.0.6 on 2020-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid_tb',
            name='respirator_required',
            field=models.CharField(default='y', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='covid_tb',
            name='medicine_applied',
            field=models.CharField(max_length=30),
        ),
    ]
